"""Loading the versioned prompt templates in ``prompts/``. PLAN.md section 3 (D7).

One template file is read by two runtimes and its version string ends up in every
``treatment.prompt_version`` it produced, so the loader has three jobs and no others:

* read the ``version`` out of the YAML frontmatter — a stored row must be traceable to the
  exact file that produced it, and a template with no declared version is a bug, not a
  default,
* substitute literal ``{{name}}`` placeholders,
* refuse to hand back a prompt that still contains one.

That last point is the reason this is a module rather than three lines of ``str.replace``.
A prompt shipped to the model with ``{{cited_ratio}}`` still in it produces a plausible,
confidently wrong classification, and nothing downstream would ever notice.

No YAML dependency: the frontmatter in ``prompts/`` is scalars and one string list, and
adding a parser dependency to read four keys is not a trade this project makes.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from functools import cache
from pathlib import Path

from jg.config import PROMPTS_DIR

_FENCE = "---"

#: ``{{name}}``, with optional inner whitespace. The same syntax the Java side substitutes.
_PLACEHOLDER = re.compile(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}")

#: HTML comments are stripped from the body before rendering. They carry instructions to
#: *developers* ("FROZEN. Do not edit this file"), never to the model, and
#: ``treatment-classify.v1.md`` documents its own placeholder syntax inside one — a literal
#: ``{{name}}`` that would otherwise trip the unsubstituted-placeholder check on every call.
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)


class PromptError(RuntimeError):
    """A prompt file or a render of it is unusable."""


class UnsubstitutedPlaceholder(PromptError):
    """A rendered prompt still contains a ``{{name}}`` placeholder. Never sent to a model."""


@dataclass(frozen=True)
class PromptTemplate:
    """One ``prompts/*.md`` file: its declared version, its frontmatter and its body."""

    #: File stem, e.g. ``treatment-classify.v1``.
    name: str
    #: The ``version:`` frontmatter value. Written to ``treatment.prompt_version``.
    version: str
    #: Everything after the frontmatter, with HTML comments removed.
    body: str
    #: Frontmatter scalars, e.g. ``cache_key`` and ``temperature``, as written.
    metadata: Mapping[str, str]
    #: The ``placeholders:`` list, as declared. Documentation, not enforcement.
    declared_placeholders: tuple[str, ...]
    path: Path

    def placeholders(self) -> tuple[str, ...]:
        """Placeholder names actually present in the body, in first-appearance order."""
        seen: dict[str, None] = {}
        for match in _PLACEHOLDER.finditer(self.body):
            seen.setdefault(match.group(1), None)
        return tuple(seen)

    def render(self, **values: object) -> str:
        """Substitute every ``{{name}}`` and refuse to return a prompt with one left.

        Strict in both directions. A value for a placeholder the body does not contain is a
        typo rather than a harmless extra, and ``None`` is rejected outright: an absent
        ``ratio_summary`` or an unknown court is a real state in this corpus (PLAN.md
        section 4 on JSpecify says so about the Java side) and the caller has to decide what
        the model should be told about it, because ``""`` silently deletes a whole section
        of the prompt.
        """
        present = set(self.placeholders())
        unknown = sorted(set(values) - present)
        if unknown:
            raise PromptError(
                f"{self.name}: no placeholder(s) {', '.join(unknown)} in {self.path}; "
                f"the template declares {', '.join(present) or '(none)'}"
            )
        for key, value in values.items():
            if value is None:
                raise PromptError(
                    f"{self.name}: placeholder {key!r} was given None. Pass the text the "
                    "model should see for a missing value instead."
                )

        def replace(match: re.Match[str]) -> str:
            name = match.group(1)
            if name not in values:
                return match.group(0)
            return str(values[name])

        rendered = _PLACEHOLDER.sub(replace, self.body)
        leftover = _PLACEHOLDER.findall(rendered)
        if leftover:
            raise UnsubstitutedPlaceholder(
                f"{self.name}: placeholder(s) {', '.join(sorted(set(leftover)))} were never "
                "substituted. Refusing to send an incomplete prompt to the model."
            )
        return rendered


def split_frontmatter(text: str) -> tuple[dict[str, str | list[str]], str]:
    """``(frontmatter, body)``. A file with no leading ``---`` fence has empty frontmatter.

    Understands exactly what ``prompts/`` uses: ``key: value`` scalars and a ``key:`` line
    followed by ``  - item`` entries. Anything else raises rather than being guessed at.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != _FENCE:
        return {}, text

    end = next(
        (index for index, line in enumerate(lines[1:], start=1) if line.strip() == _FENCE), None
    )
    if end is None:
        raise PromptError("frontmatter opened with '---' but never closed")

    front: dict[str, str | list[str]] = {}
    current: str | None = None
    for raw_line in lines[1:end]:
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        stripped = raw_line.strip()
        if stripped.startswith("- "):
            if current is None:
                raise PromptError(f"list item {stripped!r} before any key in frontmatter")
            entry = front.setdefault(current, [])
            if not isinstance(entry, list):
                raise PromptError(f"key {current!r} has both a scalar and list items")
            entry.append(stripped[2:].strip())
            continue
        if ":" not in stripped:
            raise PromptError(f"frontmatter line {stripped!r} is neither 'key: value' nor '- item'")
        key, _, value = stripped.partition(":")
        current = key.strip()
        value = value.strip()
        if value:
            front[current] = value
    return front, "\n".join(lines[end + 1 :])


def parse_prompt(text: str, *, name: str, path: Path) -> PromptTemplate:
    """Parse one template's text. Pure, so the loader is testable without a file."""
    front, body = split_frontmatter(text)
    version = front.get("version")
    if not isinstance(version, str) or not version:
        raise PromptError(
            f"{name}: no 'version' in the frontmatter of {path}. Every stored classification "
            "records the prompt version that produced it (CLAUDE.md rule 7), so a template "
            "without one cannot be used."
        )
    declared = front.get("placeholders", [])
    metadata = {
        key: value for key, value in front.items() if isinstance(value, str) and key != "version"
    }
    return PromptTemplate(
        name=name,
        version=version,
        body=_HTML_COMMENT.sub("", body).strip(),
        metadata=metadata,
        declared_placeholders=tuple(declared) if isinstance(declared, list) else (),
        path=path,
    )


def load_prompt(name: str, directory: Path = PROMPTS_DIR) -> PromptTemplate:
    """Load ``prompts/<name>.md``. ``name`` may carry the ``.md`` suffix or not. Uncached."""
    stem = name[:-3] if name.endswith(".md") else name
    path = directory / f"{stem}.md"
    if not path.is_file():
        available = ", ".join(sorted(p.stem for p in directory.glob("*.md"))) or "(none)"
        raise PromptError(f"no prompt {stem!r} in {directory}. Available: {available}")
    return parse_prompt(path.read_text(encoding="utf-8"), name=stem, path=path)


@cache
def prompt_template(name: str) -> PromptTemplate:
    """Cached :func:`load_prompt`. Templates are frozen files; reading one twice is waste."""
    return load_prompt(name)
